config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "", path_names: {sign_in: 'login', sign_up: 'register', sign_out: 'logout'}

  # get "pages/:id", to: "pages#show", as: 'pages', id: /\d+/
  get "pages/:page_path", to: "pages#show", as: 'pages'

  # for cars detailed page
  get "pages/car/:id", to: "pages#show", as: "cars", id: /\d+/

  # for cart
  get "pages/cart/:cart", to: "pages#show", as: "cart"

  # for checkout
  post "pages/checkout/:checkout", to: "pages#show", as: "checkout"

  # for payment
  post "pages/pay/:pay", to: "pages#show", as: "pay"

  # add the show action to resources
  resources :pages, only: [:show]

  root to: 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # home page index action
  # @param
  # @return void
  def index
    
    # get products to be displayed
    # @cars_to_be_displayed = Car.order("RAND()").limit(10)
    # @cars_to_be_displayed = Car.order("id").page(params[:page]).per(4)

    # # cars to be displayed (using query function from model)
    # @cars_to_be_displayed = Car.search(params[:category], params[:search], params[:page])

    # check if search was requested
    if params[:search]

      # get parameters values
      category = params[:category]
      search_item = params[:search]

      # CTS - check the type of search / filter
      if category == 'category_id'

        @cars_to_be_displayed = Car.where(:category => search_item).order("id").page(params[:page]).per(4)

      else

        @cars_to_be_displayed = Car.where("lower(#{category}) LIKE ?", "%#{search_item.downcase}%").order("id").page(params[:page]).per(4)

      end#--end CTS

    # if there is no search request, display everything
    else

      @cars_to_be_displayed = Car.order("id").page(params[:page]).per(4)

    end

    # variables to be used in the search and filter queries
    @search_param = params[:search]
    @category_param = params[:category]

    # # testing dotenv file (needs to restart the server for every change)
    # @envTest = ENV['TEST']

  end#end of index ACTION

end#--end of HomeController CLASS

app/helpers/home_helper.rb
module HomeHelper

end

app/views/home/_home.html.slim
.container
  .fluid_container.one
    .container
    .jumbotron.container-fluid id='site_banner'
    /  .jumbotron
    /   h1
    /    span.one KCars
    /    span.two  &
    /    span.three  Christmas Deals
    /   h1
    /    span.four Your
    /    span.six  Dream Car TODAY!

    / / DROPDOWN MENU
    / .dropdown
    /   a.dropdown data-target="#" data-toggle="dropdown" href="page.html"
    /     | Dropdown
    /     b.caret
    /   ul.dropdown-menu
    /     li
    /       = link_to 'test', '#', :onclick => 'alert("Please no!")'
    /     li
    /       a href="#"  Another action

    // testing dotenv file
    /h1 = @envTest

    / filter by Car category_id
    .form-inline.my-2.my-lg-0 id='filterbar'
      | Filter by:
      = form_tag(root_path, :method => "get") do
        = select_tag 'category', options_for_select([['All', 'all'], ['Car Size', 'category_id'], ['Deals', 'status']], @category_param), :onchange => "this.form.submit();", :id => 'category_select'

        / check if category of filtering
        - if @category_param == 'category_id'
          = form_tag(root_path, :method => "get") do
            = select_tag 'search', options_for_select([ ['All', ''], ['Economic', 1], ['Standard', 2], ['Full Size', 3] ], @search_param), :onchange => "this.form.submit();", :id => 'carSize_select'

        - if @category_param == 'status'
          = form_tag(root_path, :method => "get") do
            = select_tag 'search', options_for_select([ ['All', ''], ['On Sale', 'sale'], ['New', 'new'], ['Updated', 'updated'] ], @search_param), :onchange => "this.form.submit();"

        = link_to 'Reset', root_path, :class => 'btn btn-secondary', :id => 'filter_reset_btn'


        / / send data to coffeescript
        / = content_tag "div", id: "test2", data: {item: "hello"} do

      / = form_tag(root_path, :method => "get") do
      /   = select_tag 'category', options_for_select([['All', ''], ['Car Size', 'category_id'], ['Deals', 'deals']]), :onchange => "this.form.submit();"
      / - if @category == 'category_id'
      /   = form_tag(root_path, :method => "get") do
      /     = select_tag 'search', options_for_select([ ['All', ''], ['Economic', 1], ['Standard', 2], ['Full Size', 3] ]), :onchange => "this.form.submit();"

      / = form_tag(root_path, :method => "get", id: "search-form") do
      /   = select_tag 'category', options_for_select([['Car Size', 'category_id'], ['test', 8]]), :onchange => "this.form.submit();"
      /   = select_tag 'search', options_for_select([ ['All', ''], ['Economic', 1], ['Standard', 2], ['Full Size', 3] ]), :onchange => "this.form.submit();"
      /   = " "
      /   = submit_tag "Filter", :name => nil, :class => "btn-secondary"
    br/

    / / filter by Car category_id
    / .form-inline.my-2.my-lg-0 id='filterbar'
    /   = form_tag(root_path, :method => "get", id: "search-form") do
    /     = select_tag 'category', options_for_select([['Car Size', 'category_id']]), { :class => 'form-control' }
    /     = select_tag 'search', options_for_select([ ['All', ''], ['Economic', 1], ['Standard', 2], ['Full Size', 3] ]), { :class => 'form-control' }
    /     = " "
    /     = submit_tag "Filter", :name => nil, :class => "btn-secondary"
    / br/

    / check if there was a search
    - if @cars_to_be_displayed.size == 0
      h1 = "Unfortunately no match were found for '#{@search_param}' =("

    - else
      / creating row to store products
      .row.text-center
        / loop through all the cars to be displayed
        - @cars_to_be_displayed.each do |car|
          / getting image file name (trim the full path)
          - image_file_name = extract_car_image_filename(car)
          / creating product card -- https://mdbootstrap.com/components/cards/#cascading-cards
          .col-lg-3.col-md-6.mb-4
            .card
              img = image_tag(image_file_name)
              .card-body
                h4.card-title = car.make + " " + car.model + " " + car.year.to_s
                h5.card-text = to_str_currency(car.price)
                p.card-text = limit_text_length(car.description, 80)
              .card-footer
                a = link_to 'Find Out More!', cars_path(car.id), { :class => 'btn btn-primary'}

    / adding pagination wiz kaminari and styling with another gem
    = paginate @cars_to_be_displayed, :theme => 'twitter-bootstrap-3'

    / h1 = session[:cart]

app/views/home/index.html.slim
= render  :partial => 'home',
          :locals => {  :home_page => true }