config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "", path_names: {sign_in: 'login', sign_up: 'register', sign_out: 'logout'}

  # get "pages/:id", to: "pages#show", as: 'pages', id: /\d+/
  get "pages/:page_path", to: "pages#show", as: 'pages'

  # for cars detailed page
  get "pages/car/:id", to: "pages#show", as: "cars", id: /\d+/

  # for cart
  get "pages/cart/:cart", to: "pages#show", as: "cart"

  # for checkout
  post "pages/checkout/:checkout", to: "pages#show", as: "checkout"

  # for payment
  post "pages/pay/:pay", to: "pages#show", as: "pay"

  # add the show action to resources
  resources :pages, only: [:show]

  root to: 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title KCars
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    /! Bootstrap core CSS
    /! (( not being used. file in main.css.scss.))
    / link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"

    / favicon icon
    / link href="http://www.keiji.pcriot.com/site/css/img/K_LOGO.png" rel="icon"
    link rel="icon" type="image/png" href="#{get_klogo_icon()}"

  body
    - if notice
      .container
        p.alert.alert-success = notice
    - if alert
      .container
        p.alert.alert-danger = alert
    / nav bar
    / nav.navbar.navbar-default.navbar-static-top
    nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark role="navigation"
      / brand name: icon
      img.navbar-brand = image_tag("k_logo_medium.png")

      .collapse.navbar-collapse
        ul.navbar-nav.mr-auto
          / home link (fixed)
          li.nav-item.active id='home' = link_to "Home", root_path, { :class => "nav-link" }

          / other menu items (check if display_in_menu is true)
          - @page_nav.each do |page|
            - if page.display_in_menu
              li.nav-item.active = link_to page.title, page_path(page.page_path), { :class => "nav-link" }
              / / to get path with id
              / li.nav-item.active = link_to page.title, page_path(page.id), { :class => "nav-link" }
              / / to get path with "page_path" column name (eg: .../about)
              / li.nav-item.active = link_to page.title, page.page_path, { :class => "nav-link" }
              / / to get path with page_path controler name + "page_path" column name (eg: ...pages/about)

        p.navbar-text.pull-right id='loginCtrl'
          - if user_signed_in?
            / .glyphicon.glyphicon-shopping-cart = "cart: #{session[:cart]} | "
            - if session[:cart]
              = link_to "cart: #{sum_hash_array_values(session[:cart])} ", cart_path(:cart => true), :class => 'navbar-link'
              = " | "
            | Logged in as: <strong>#{current_user.email}</strong> |
            = link_to ' Edit profile', edit_user_registration_path, {:class => 'navbar-link'}
            = " | "
            = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
          - else
            = link_to "Login", new_user_session_path, {:class => 'navbar-link'}
            = " | "
            = link_to "Sign up", new_user_registration_path, {:class => 'navbar-link'}

        / / sign in options (fixed)
        / ul.nav.navbar-nav
        /   li
        /     p.navbar-btn
        /       a.btn.btn-primary href="#" Login
        /   li
        /     p.navbar-btn
        /       a.btn.btn-default href="#" Sign In

        / / tried using glyphicon
        / ul.nav.navbar-nav.navbar-right
        /   li.glyphicon.glyphicon-log-in
        /     span Login
        /   li.glyphicon.glyphicon-user
        /     span Sign In

    / second nav bar for the search function
    nav.navbar.navbar-toggleable-sm.bg-inverse.navbar-inverse.fixed-top id='nav2'
      .container-fluid id='searchTool'
        .row-fluid
          / /! select menu for search
          / .col-sm-4
          /   select.form-control
          /     option value="model"  Model
          /     option value="make"  Make
          /     option value="economy"  Economy
          /     option value="standard"  Standard
          /     option value="fullsize"  Full Size

          /! search bar
          / check this: http://www.rymcmahon.com/articles/2
          / and this: http://www.korenlc.com/creating-a-simple-search-in-rails-4/
          / and this: https://www.youtube.com/watch?v=eUtUquKc2qQ
          .form-inline.my-2.my-lg-0 id='searchbar'
            = form_tag(root_path, :method => "get", id: "search-form") do
              = select_tag 'category', options_for_select(([['Model', 'model'], ['Make', 'make']])), { :class => 'form-control' }
              = text_field_tag :search, params[:search], placeholder: "Search Cars", :id => "search_text"
              = submit_tag "Search", :name => nil

    = yield
    /! Site footer
    .panel-footer id="footer"
      p © KCar | Privacy | All rights reserved.